Use dmb ish instead of dmb st and dmb sy
I had problems building rpmalloc using GCC 7.2.0 on Slackware ARM, and got many of these errors:

Error: selected processor does not support `dmb sy' in ARM mode
Error: selected processor does not support `dmb st' in ARM mode

Looking at https://gcc.gnu.org/ml/gcc-patches/2014-11/msg01272.html, it seems that it is safe to replace dmb sy (and I assume) dmb st with dmb ish. I could then compile rpmalloc and everything seems to work fine (I could use programs that depend on rpmalloc fine).

Note that I haven't run any sort of extensive tests, and I'm not entirely sure if dmb ish is the correct replacement for dmb st, but this should work.